language: python

python:
  - "2.7"

notifications:
  email: false

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-3.4.2-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -n test-environment python=$TRAVIS_PYTHON_VERSION nose numba=0.11.1 numpy scipy
  - source activate test-environment
  # install packages from binstar that are not available from continuum analytics
  - conda install -c https://conda.binstar.org/richli pyfftw
  - python setup.py install

script: make test
